### ISSUE TITLE
code 排版略显拥挤

### ISSUE THREAD

**Issue by xiongchengqing** [blinkfox/typora-vue-theme#1]
code 排版略显拥挤, 如下图
<img width="849" alt="wx20180605-110314 2x" src="https://user-images.githubusercontent.com/1636616/40952966-320cadfc-68b0-11e8-97b6-e2904d5cd800.png">

**Comment by blinkfox** [comment]
@xiongchengqing 你好，code排版拥挤的问题是由于字体引起的，我又新引入了`Roboto Mono`字体，你可以下载最新的`vue.css`和`vue`文件夹中的字体覆盖即可。
