### ISSUE TITLE
流程图、时序图等渲染问题

### ISSUE THREAD

**Issue by cnwoodgithub** [blinkfox/typora-vue-theme#18]
在使用mermaid，flow等进行流程图、时序图等绘制时，在编辑时，渲染出的图例会重叠。

**Comment by andyfleming** [comment]
<img width="872" alt="Screen Shot 2019-04-10 at 4 51 07 PM" src="https://user-images.githubusercontent.com/721038/55921281-f0924400-5bb0-11e9-8eee-839a76398acf.png">

I fixed this by editing the CSS and deleting the `margin: 0.8rem 0 !important;` line in the `#write .md-fences` rule.

**Comment by blinkfox** [comment]
@andyfleming Thanks.

**Comment by cnwoodgithub** [comment]
> <img alt="Screen Shot 2019-04-10 at 4 51 07 PM" width="872" src="https://user-images.githubusercontent.com/721038/55921281-f0924400-5bb0-11e9-8eee-839a76398acf.png">
> 
> I fixed this by editing the CSS and deleting the `margin: 0.8rem 0 !important;` line in the `#write .md-fences` rule.

Thanks.

**Comment by MAGI003769** [comment]
> <img alt="Screen Shot 2019-04-10 at 4 51 07 PM" width="872" src="https://user-images.githubusercontent.com/721038/55921281-f0924400-5bb0-11e9-8eee-839a76398acf.png">
> 
> I fixed this by editing the CSS and deleting the `margin: 0.8rem 0 !important;` line in the `#write .md-fences` rule.

Thanks, it works well now
