### ISSUE TITLE
Highlight renders not correctly

### ISSUE THREAD

**Issue by kuylensa** [blinkfox/typora-vue-theme#2]
Hello,

I noticed that when I highlight text, it doesn't render correctly.
Screenshot builtin theme "Github"
![screen shot 2018-06-05 at 11 15 49](https://user-images.githubusercontent.com/2338754/40966856-ebcae83e-68b1-11e8-9915-a1bd25909d88.png)

and a screenshot with this theme "vue"
![screen shot 2018-06-05 at 11 16 07](https://user-images.githubusercontent.com/2338754/40966876-f44ba50c-68b1-11e8-88df-99f469466fb8.png)

Is it possible that when rendering `==` a new line/paragraph is started? And a multiline-highlight renders into one line.

Using: Version 0.9.9.16.2 on macOS

Greets,
Sam

**Comment by blinkfox** [comment]
@kuylensa Hello, I have solved this problem. you can download the latest `vue.css` file and `vue` folder to overwrite the previous files.

**Comment by kuylensa** [comment]
Indeed, thank you.
![screen shot 2018-06-06 at 16 05 30](https://user-images.githubusercontent.com/2338754/41043146-8fd4186e-69a3-11e8-9ba5-08d05bc2268f.png)
