### ISSUE TITLE
黑色主题菜单显示颜色有问题

### ISSUE THREAD

**Issue by wjbgis** [blinkfox/typora-vue-theme#20]
黑色主题在软件一体化模式下菜单文字颜色和背景颜色一样了，难以分辨。

**Comment by blinkfox** [comment]
@wjbgis 你好有截图吗？我在 MAC 上看没有这个问题呢？

**Comment by wjbgis** [comment]
在偏好设置中窗口样式选择一体化
![1](https://user-images.githubusercontent.com/33862138/57202861-d2b3d580-6fdc-11e9-89d8-8644961dab90.png)
然后选项面板变成了这样
![2](https://user-images.githubusercontent.com/33862138/57202902-4c4bc380-6fdd-11e9-818f-4cddfece7df5.png)
正常应该是这样的：
![3](https://user-images.githubusercontent.com/33862138/57202907-566dc200-6fdd-11e9-8490-c87039f12081.png)
