### ISSUE TITLE
使用有序列表不显示数字

### ISSUE THREAD

**Issue by GameHoo** [blinkfox/typora-vue-theme#3]
### 源代码
![image](https://user-images.githubusercontent.com/15765595/41918568-38a2d318-798f-11e8-8c0c-6193f8f9ed7a.png)

### 显示效果
![image](https://user-images.githubusercontent.com/15765595/41918619-4fb1246a-798f-11e8-87e5-9ae474b83ae8.png)

### 切换使用其他主题的效果（Github）
![image](https://user-images.githubusercontent.com/15765595/41918692-6e59660c-798f-11e8-8efa-7eda8363e76d.png)

**Comment by blinkfox** [comment]
@GameHoo 你好，我在 Windows 和 Mac 下都用Typora打开了和你相同的文字的效果，都没有出现你这种现象呢，我看你这个应该是`1`这个数字没显示出来吧。

我打开的效果如下：

![效果](http://static.blinkfox.com/typora_effeict_01.png)

**Comment by GameHoo** [comment]
https://pan.baidu.com/s/1OyfCfO798OPQ6q61LJhSww
我把我的源文件上传了
有时间可以看看
![image](https://user-images.githubusercontent.com/15765595/42016985-1970d11e-7ae0-11e8-828e-48b9d3915185.png)

**Comment by blinkfox** [comment]
@GameHoo 我把你的笔记在 Windows、Linux 和 Mac 下都用 Typora 打开了依然没有你的问题呢，甚至我让同事在他们的环境都没复现你这样的问题。

我猜你应该是前端人员吧，Typora 里面本质上也是一个`V8`引擎，你可以用调试模式（类似Chrome的调试）看看，有没有控制有序列表的显示样式，样式为：`list-style-type`，如果它的值是`decimal`的话，就会显示成`1`, `2`, `3`之类的，没显示应该跟你的环境有些关系，你可以在`vue.css`里面加上如下的样式，试试看：

```css
ol {
    list-style-type: decimal;
}
```

调试效果如下：

![调试效果](http://static.blinkfox.com/typora_effeict_02.png)

另外，我看你这些有序列表的使用更倾向于`1`, `2`, `3`等标题的含义了，而有序列表和无序列表的使用更多的是用于**连续的**、**不跨大段落**的情况，所以，我建议你应该直接把它们做出`4`级**标题**其实更合理点儿。效果如下：

![标题效果](http://static.blinkfox.com/typora_effeict_03.png)

**Comment by zhuimin** [comment]
您好，我也出现了这个问题，在Vue主题下有序编号会变成点，但是切换到其他主题就能显示数字了。

**Comment by blinkfox** [comment]
@zhuimin 有具体的Markdown内容吗？我看看

**Comment by blinkfox** [comment]
@GameHoo 你这个太高端了，我都没验证测试环境

**Comment by yinyeya** [comment]
我也遇到了同样的问题。在4k显示屏文本缩放250%条件下测试的，系统windows10最新版。我尝试添加了`list-type-style: decimal;`, 部分有些序列表数字可以正常显示了，但有些还是不能。尤其是在不同级别的标题和有序列表混搭时，有序列表数字会消失。我尝试了自己的md文件和typora-theme-toolkit里的md文件，情况类似。

**Comment by yinyeya** [comment]
@blinkfox 我不是很懂CSS和前端啊。请问你能估计大概是代码的那部分出问题了么？这样我可以试着改。
