### ISSUE TITLE
如何让代码块中的代码字体不加粗

### ISSUE THREAD

**Issue by ThisisWilli** [blinkfox/typora-vue-theme#34]
很喜欢这3个主题，但是粗体代码看上去不太适应，但是css代码又不太会改，请作者指点一下，谢谢

**Comment by sst2010** [comment]
Which component's style do you want to update ?? @ThisisWilli 

Please, share the markdown for which you want to modify the styles.
Example,
- If you want to update the styles of `heading 1`, please share the markdown:
   `# Heading Level 1`

I might be able to share some sample styles for assistance. 😃

**Comment by ThisisWilli** [comment]
Thanks for you reply
When I insert code block in my markdown file in Vue dark oceanicnext theme, the codes in code block are bold and I want them be light or normal. But I do not now how to change this  font-weight in css file.

**Comment by ThisisWilli** [comment]
> Which component's style do you want to update ?? @ThisisWilli
> 
> Please, share the markdown for which you want to modify the styles.
> Example,
> 
> * If you want to update the styles of `heading 1`, please share the markdown:
>   `# Heading Level 1`
> 
> I might be able to share some sample styles for assistance. 😃
> 
> > Translated for better reference:
> 
> どのコンポーネントのスタイルを更新しますか？ あずきっく
> 
> スタイルを変更するマークダウンを共有してください。
> 例、
> 
> * 見出し1のスタイルを更新する場合は、マークダウンを共有してください：
>   `＃見出しレベル1`
> 
> 支援のためにいくつかのサンプルスタイルを共有できる場合があります。😃

Thanks for you reply
When I insert code block in my markdown file in Vue dark oceanicnext theme, the codes in code block are bold and I want them be light or normal. But I do not now how to change this font-weight in css file.

**Comment by sst2010** [comment]
@ThisisWilli 

I just tested a solution. It's quite simple. Please follow the steps below:

### Step 1: Open Typora Preferences
![image](https://user-images.githubusercontent.com/25411283/80492740-13d98e00-8982-11ea-8e0f-ad23b8f618da.png)
- Open `Preferences` in Typora & click on the button `Open Theme folder` highlighted above.
- A folder named **`themes`** will open.

### Step 2: Find the theme's CSS
- In the folder opened, you should be able to see a file named similar to `vue-dark.css`.
- The file name can be different depending on the theme name. My themes name is `Vue Dark`.

### Step 3: Create custom CSS for the theme
- In this same folder, create a file with the name `vue-dark.user.css`.
- Note that the file name has to be in the same format as shown above. Although, depending on your theme name, the file name might be different.
- In this created file, paste the code below:
  ```
  #write .md-fences
  {
      font-weight: 400 !important;
  }
  
  ```
- Save the file.
- Restart `Typora`.

The issue should have been fixed. Note that `font-weight: 300 !important` might have the same effect as in my case, the font file for weight 300 was not available.

Feel free to reach out in case of any queries. Have a great day !!

**Comment by ThisisWilli** [comment]
> @ThisisWilli
> 
> I just tested a solution. It's quite simple. Please follow the steps below:
> 
> ### Step 1: Open Typora Preferences
> ![image](https://user-images.githubusercontent.com/25411283/80492740-13d98e00-8982-11ea-8e0f-ad23b8f618da.png)
> 
> * Open `Preferences` in Typora & click on the button `Open Theme folder` highlighted above.
> * A folder named **`themes`** will open.
> 
> ### Step 2: Find the theme's CSS
> * In the folder opened, you should be able to see a file named similar to `vue-dark.css`.
> * The file name can be different depending on the theme name. My themes name is `Vue Dark`.
> 
> ### Step 3: Create custom CSS for the theme
> * In this same folder, create a file with the name `vue-dark.user.css`.
> * Note that the file name has to be in the same format as shown above. Although, depending on your theme name, the file name might be different.
> * In this created file, paste the code below:
>   ```
>   #write .md-fences
>   {
>       font-weight: 400 !important;
>   }
>   ```
> * Save the file.
> * Restart `Typora`.
> 
> The issue should have been fixed. Note that `font-weight: 300 !important` might have the same effect as in my case, the font file for weight 300 was not available.
> 
> Feel free to reach out in case of any queries. Have a great day !!

Thanks for your help!!! it works
hope you have a nice day!😊

**Comment by sst2010** [comment]
Glad it worked !! You too have a nice day.
