### ISSUE TITLE
支持微软雅黑字体么？

### ISSUE THREAD

**Issue by tengshe789** [blinkfox/typora-vue-theme#4]

**Comment by blinkfox** [comment]
@tengshe789 不支持额，如果你想用微软雅黑显示的话，得自己改几行`css`代码就行，主要修改如下：

1. 全局的字体修改是在`vue.css`文件第`263`行，在`font-family`属性的最前面添加`微软雅黑`的名称即可，这样就可以让`微软雅黑`的字体显示优先级最高，系统读取不到微软雅黑时，再依次使用后面类型的字体，代码改动如下:

```css
font-family: 微软雅黑, Source Sans Pro, Helvetica Neue, Arial, sans-serif !important;
```

2. 代码块和行内代码的字体修改分别是在`vue.css`文件第`551`、`564`行，改法同前面类似，都是在`font-family`属性的最前面添加`微软雅黑`:

```css
font-family: 微软雅黑, Roboto Mono, Source Sans Pro, Monaco, courier, monospace !important;
```

```css
font-family: 微软雅黑, Source Sans Pro, Roboto Mono, Monaco, courier, monospace !important;
```

**Comment by tengshe789** [comment]
谢谢，成功了~
