### ISSUE TITLE
Index of list item cannot be seen on high definition screen

### ISSUE THREAD

**Issue by BYJRK** [blinkfox/typora-vue-theme#8]
Hello there. I found that when using Vue theme on Windows high definition screen (e.g. 4K, 200% scale), the index of list items cannot be seen (more specifically, the first digit cannot be seen, that is to say, `12.` will only shows `2.`, while `1.` will shows `.`).

Can anyone here help me fix this problem?

![image](https://user-images.githubusercontent.com/11771667/48931480-7e86ce80-ef31-11e8-8d54-45dc7bc287ce.png)

**Comment by blinkfox** [comment]
I have time to reproduce and solve this problem later.

**Comment by NoDocCat** [comment]
I want solve this issue. but i don't have 4k screen.
I will try setting DPI to 200% on my screen. hope can reappear this issue.

**Comment by NoDocCat** [comment]
Now, I reappear this issue and found the reason.
On vue.css: 286
```css
#write ol li {
    padding-left: 0.5rem;
}
```
But i don't know this code whether has other effect.
@blinkfox Can i delete it?

**Comment by blinkfox** [comment]
@NoDocCat You can delete it and check it out on `4k`, `2k` or normal screen. If the display is normal, then it is ok.

**Comment by NoDocCat** [comment]
@blinkfox 
I try to use text-indent replace padding-left.
But, I found some differences

first image is old theme.
![100-old](https://user-images.githubusercontent.com/20502666/49450337-b9351480-f817-11e8-9f4d-55048d25c247.png)
![100-new](https://user-images.githubusercontent.com/20502666/49450352-c520d680-f817-11e8-85c4-57c428cc6b96.png)

look secondary list, it's left margin to shrink.
Do you think this is acceptable?

**Comment by NoDocCat** [comment]
Add some images.
I sure it work at 200% DPI and 150% DPI

-  200% new theme
-  200% old theme
-  150% new theme
-  150% old theme

![200-new](https://user-images.githubusercontent.com/20502666/49450970-1d0c0d00-f819-11e8-80dd-630be1f1cea6.png)
![200-old](https://user-images.githubusercontent.com/20502666/49450981-21d0c100-f819-11e8-91c3-4688a06036f1.png)
![150-new](https://user-images.githubusercontent.com/20502666/49450985-24cbb180-f819-11e8-9cd9-69d68ac5cae4.png)
![150-old](https://user-images.githubusercontent.com/20502666/49450990-272e0b80-f819-11e8-9df9-7593f57a727a.png)

**Comment by blinkfox** [comment]
I can accept, the difference is small.
